// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Data;

#nullable disable

namespace STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719025506_initdb")]
    partial class initdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.ProjectAllocation", b =>
                {
                    b.Property<int>("ProjectAllocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectAllocationID"));

                    b.Property<DateTime>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<string>("OverAllGrade")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("ProjectEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProjectStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("TotalCompletedTasks")
                        .HasColumnType("int");

                    b.Property<int>("TotalTasksGiven")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectAllocationID");

                    b.HasIndex("FacultyID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("StudentID");

                    b.ToTable("SPM_ProjectAllocation");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.ProjectMaster", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectID");

                    b.ToTable("SPM_ProjectMaster");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("SPM_Role");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.TaskPriorityMaster", b =>
                {
                    b.Property<int>("TaskPriorityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskPriorityID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskPriorityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaskPriortyCssClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("TaskPriorityID");

                    b.HasIndex("TaskPriorityName")
                        .IsUnique();

                    b.ToTable("SPM_TaskPriority");

                    b.HasData(
                        new
                        {
                            TaskPriorityID = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPriorityName = "Low",
                            TaskPriortyCssClass = "tone-neutral"
                        },
                        new
                        {
                            TaskPriorityID = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPriorityName = "Moderate",
                            TaskPriortyCssClass = "tone-warning"
                        },
                        new
                        {
                            TaskPriorityID = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPriorityName = "Critical",
                            TaskPriortyCssClass = "tone-danger"
                        });
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.TaskStatusMaster", b =>
                {
                    b.Property<int>("TaskStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskStatusID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskStatusCssClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaskStatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("TaskStatusID");

                    b.HasIndex("TaskStatusName")
                        .IsUnique();

                    b.ToTable("SPM_TaskStatus");

                    b.HasData(
                        new
                        {
                            TaskStatusID = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskStatusCssClass = "tone-warning",
                            TaskStatusName = "Pending"
                        },
                        new
                        {
                            TaskStatusID = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskStatusCssClass = "tone-info",
                            TaskStatusName = "Ongoing"
                        },
                        new
                        {
                            TaskStatusID = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskStatusCssClass = "tone-success",
                            TaskStatusName = "Completed"
                        },
                        new
                        {
                            TaskStatusID = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskStatusCssClass = "tone-danger",
                            TaskStatusName = "Cancelled"
                        });
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.Tasks", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<decimal>("AssignedScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EarnedScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("FacultyRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProjectAllocationID")
                        .HasColumnType("int");

                    b.Property<string>("StudentRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("TaskAssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TaskCompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TaskDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskPriorityID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TaskStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskStatusID")
                        .HasColumnType("int");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("TaskID");

                    b.HasIndex("ProjectAllocationID");

                    b.HasIndex("TaskPriorityID");

                    b.HasIndex("TaskStatusID");

                    b.ToTable("SPM_Task");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicturePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserTypeID");

                    b.ToTable("SPM_User");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.UserRole", b =>
                {
                    b.Property<int>("RolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("SPM_UserRole");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserTypeID");

                    b.HasIndex("UserTypeName")
                        .IsUnique();

                    b.ToTable("SPM_UserType");

                    b.HasData(
                        new
                        {
                            UserTypeID = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Full system access",
                            UserTypeName = "Admin"
                        },
                        new
                        {
                            UserTypeID = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Supervises student projects",
                            UserTypeName = "Faculty"
                        },
                        new
                        {
                            UserTypeID = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Works on assigned projects",
                            UserTypeName = "Student"
                        });
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.ProjectAllocation", b =>
                {
                    b.HasOne("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.User", "Faculty")
                        .WithMany("ProjectAllocationsAsFaculty")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.ProjectMaster", "ProjectMaster")
                        .WithMany("ProjectAllocations")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.User", "Student")
                        .WithMany("ProjectAllocationsAsStudent")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("ProjectMaster");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.Tasks", b =>
                {
                    b.HasOne("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.ProjectAllocation", "ProjectAllocation")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectAllocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.TaskPriorityMaster", "TaskPriority")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskPriorityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.TaskStatusMaster", "TaskStatus")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectAllocation");

                    b.Navigation("TaskPriority");

                    b.Navigation("TaskStatus");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.User", b =>
                {
                    b.HasOne("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.UserRole", b =>
                {
                    b.HasOne("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.ProjectAllocation", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.ProjectMaster", b =>
                {
                    b.Navigation("ProjectAllocations");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.TaskPriorityMaster", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.TaskStatusMaster", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.User", b =>
                {
                    b.Navigation("ProjectAllocationsAsFaculty");

                    b.Navigation("ProjectAllocationsAsStudent");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("STUDENTPROJECTMANAEMENTSYSTEMBACKEND.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
